#This is an example config format that you can change as per your choice and pass to the main commandline
    # config.yaml
    ## Where the samples will be written
    save_data: ../Data/TrainingData/<ds.name>
    ## Where the vocab(s) will be written
    src_vocab: ../Data/TrainingData/<ds.name>/src_vocab
    tgt_vocab: ../Data/TrainingData/<ds.name>/tgt_vocab
    ## Where the model will be saved
    save_model: ../NLP/Models
    num_threads: 100
    overwrite: True
    share_vocab: True
    dynamic_dict: 1
    # Corpus opts:
    data:
        corpus_1:
            path_src: ../Data/train_src.txt
            path_tgt: ../Data/train_tgt.txt
        valid:
            path_src: ../Data/val_src.txt
            path_tgt: ../Data/val_src.txt
    # Remove or modify these lines for bigger files
    train_steps: 10000
    valid_steps: 2000
    path_src:  ../Data/train_src.txt
        path_tgt: ../Data/train_tgt.txt
        transforms: [filtertoolong]
    valid:
        path_src: {ds.val.source}
        path_tgt: {ds.val.target}
#### Filter
src_seq_length: 300
tgt_seq_length: 300
# Train on a single GPU
# world_size: 1
# gpu_ranks: [0]
"""
